name: 🐛 Signaler un bug
description: Signaler des bugs nous permet d'améliorer Scola !
title: "[Bug]: "

body:
  - type: textarea
    attributes:
      label: Description du bug
      description: Plus il y a de détails, plus vite nous pourrons trouver le bug !
      placeholder: La connexion à mon établissement ne fonctionne pas, j'ai un chargement infini lors de la connexion
    validations:
      required: true

  - type: textarea
    attributes:
      label: Étapes à reproduire
      description: Comment pouvons-nous reproduire le bug ?
      placeholder: |
        1. Ouvrir l'application
        2. Se connecter à l'établissement
        3. Observer le comportement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comportement attendu
      description: Ce que Scola devrait faire
      placeholder: Que la connexion à mon établissement fonctionne et qu'il n'y ait pas de chargement infini
    validations:
      required: true

  - type: input
    attributes:
      label: Appareil
      description: Sur quel appareil tu as rencontré ce bug ?
      placeholder: iPhone 13, Samsung Galaxy S23...
    validations:
      required: true

  - type: input
    attributes:
      label: Version du système d'exploitation
      description: Paramètres (du Téléphone) -> À propos (Android)/Général (Apple)
      placeholder: iOS 18, Android 15...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Scola testé depuis
      description: Tu as testé/installé Scola depuis...
      options:
        - Play/App Store (version stable)
        - Play Store/TestFlight (version bêta)
    validations:
      required: true

  - type: input
    attributes:
      label: Version utilisée
      description: Paramètres (de Scola) -> Version affichée en bas de la page
      placeholder: "8.0.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Service scolaire/cantine
      description: 🎒 = Service scolaire et 🍽️ = Service de cantine
      options:
        - 🎒🦋 Pronote
        - 🎒🟦 ÉcoleDirecte
        - 🎒🟡 Skolengo
        - 🎒🏫 Universités et autres (à préciser dans la description du bug)
        - 🍽️🟢 Alise
        - 🍽️🔴 Turboself
        - 🍽️🟣 ARD
        - 🍽️🔵 Izly
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Capture(s) d'écran / vidéo"
      description: Cela permettra une résolution encore plus rapide du bug
      placeholder: Il faut cliquer sur l'icône 📎 pour pouvoir importer une/des photo(s)/vidéo(s)
    validations:
      required: false
